<!doctype html>
<head>
    <meta charset="utf-8">       
    <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="../../public/css/vektis-styles.css">
</head>
<body>
    <div class="header border-bottom border-info">
        <div class="header-inner container">
            <h1>
                Vektis-viewer
                <button onclick=OpenRegelModal() class="btn btn-danger" data-toggle="modal" data-target="#myModal"> Regels overzicht </button>
            </h1>
        </div>
    </div>
    <div class="container-fluid"> 
        <div class="row">
            <div id="standaarden-wrapper" class="col-sm-4 border border-info">
                <h3 class="border-bottom border-info">Standaarden</h3>        
                <div id="standaarden-div" class="list-container">
                
                </div>
            </div>
            <div id="regelinformatie-wrapper" class="col-sm-4 border border-info">
                <h3 class="border-bottom border-info">Regelinformatie</h3>      
                <div id="regelinformatie-div" class="list-container">
                
                </div>  
            </div> 
            <div id="gegevenselementen-wrapper" class="col-sm-4 border border-info">
                <h3 class="border-bottom border-info">Gegevenselementen</h3>      
                <div id="gegevenselementen-div" class="list-container">
                
                </div>  
            </div> 
        </div>       
    </div>

        <!-- The Modal -->
    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Modal Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="../../public/js/vektis-viewer.js"></script>
</body>