<!doctype html>
    <head>
        <meta charset="utf-8">       
        <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="../../public/css/styles.css">
    </head>
    <body class="bg-dark text-white">
        <div class="header">
            <div class="header-inner">
            <?php if(isset($_SESSION["username"])) {
                    echo "<button id='go-back-button' type='button' class='btn btn-dark navigation-button go-back-button'> <- Back </button>";
                }
                ?>
                <form id="logout-form" class='logout-form'>
                <?php if(isset($_SESSION["username"])) {
                    echo "<input id='log-out-button' type='button' name='logout' value='logout' onclick='LogOut()' class='btn btn-dark'> " .$_SESSION["username"]. " </input>";
                }
                ?>
                </form>
            </div>
        </div>
        <div class="container-fluid vh-100">