<div class="modal fade" id="loadMapModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog load-map-modal" role="document">
      <div class="modal-content load-modal-content">
        <div class="modal-header">
            <h5 class="modal-title text-muted" id="exampleModalLabel">Click the file you want to load below!</h5>
            <button id="load-map-modal-dismiss" type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>                
        </div>
        
        <div class="modal-body load-modal-body text-muted">
            <div class="container modal-container col-md-12">
                <div class="row modal-row">
                    <div class="col-md-2 load-maps-names-div">

                    </div>
                    <div class="col-md-10 preview-canvas-wrapper-div">
                        <div class="preview-map-title-div">
                            <h5 id="preview-map-neighbourhood"></h5>
                            <h5 id="preview-map-name"></h5>
                            <h6 id="preview-map-tileset"></h6>
                        </div>
                        <div class="row preview-map-canvas">
                            <canvas id="preview-map-canvas" class="visible-canvas">
                            </canvas>
                        </div>
                        <div class="preview-modal-load-map-button-div">        
                            <button id="confirm-load-map-button" class="mt-5 btn btn-success btn-lg btn-block navigation-button">
                            Load map</button>
                    </div>
                    </div>
                </div>
            </div>
        </div>

      </div>
    </div>
  </div>