<div class="modal fade" id="loadMapModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog load-map-modal" role="document">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title text-muted" id="exampleModalLabel">Click the file you want to load below!</h5>
            <button id="load-map-modal-dismiss" type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>                
        </div>
        
        <div class="modal-body text-muted">
            <div class="container col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <?php   
                            $neighbourhoods_path = '/user-folders' . '/' .$_SESSION["username"]. '/neighbourhoods';
                            $maps_path = '/user-folders'  . '/' .str_replace( " ", "_", $_SESSION["username"] ). '/maps';
                            $neighbourhoods = scandir( $_SERVER['DOCUMENT_ROOT'].$neighbourhoods_path );
                            $maps = scandir( $_SERVER['DOCUMENT_ROOT'].$maps_path  );

                            echo "<h6> Neighbourhoods </h6><hr>";

                            foreach($neighbourhoods as $neighbourhood) {
                                if ( $neighbourhood != "." && $neighbourhood != ".." ) {
                                    $url = $_SERVER['DOCUMENT_ROOT'].$neighbourhoods_path."/".$neighbourhood;
                                    $json_as_string = file_get_contents( $url, false );
                                    $json_data = json_decode($json_as_string, true);

                                    echo "<div class='load-neighbourhood-from-server'> ".$neighbourhood."<br> <ul id='".$neighbourhood."' class='map-selection-list'>";
                                    foreach(array_keys($json_data) as $key) {
                                       $map = $json_data[$key];
                                       $tilesheet = $map['tileSet'];
                                       $grid = implode(",", array_merge(...$map['grid']));
                                       $rows = $map['rows'];
                                       $columns = $map['columns'];

                                       echo "<li id='$key' neighbourhood='$neighbourhood' tilesheet='$tilesheet' grid='$grid' rows='$rows' columns='$columns' class='map-selection-list-item'> ". $key . "<input type='radio' style='float: right;' name='map-preview-input' id='$key.radio' class='map-selection-list-item-radio' />";
                                       if ( isset($map["subMaps"]) ) {
                                            $subMaps = $map["subMaps"];
                                            echo "<ul class='map-selection-list'>";
                                            foreach(array_keys($subMaps) as $innerKey) {
                                                $subMap = $subMaps[$innerKey];
                                                $tilesheet = $subMap['tileSet'];
                                                $grid = implode(",", array_merge(...$subMap['grid']));
                                                $rows = $subMap['rows'];
                                                $columns = $subMap['columns'];

                                                echo "<li id='$innerKey' neighbourhood='$neighbourhood' tilesheet='$tilesheet' grid='$grid' rows='$rows' columns='$columns' class='map-selection-list-item-inner'>". $innerKey."<input type='radio' style='float: right;' name='map-preview-input' id='$innerKey.radio' class='map-selection-list-item-radio' /></li>";
                                            }
                                            echo "</ul>";  
                                       }
                                       echo "</li>";

                                    }
                                    
                                    echo "</ul></div>";                        
                                }
                            }

                            echo "<br/><h6> Individual maps </h6><hr>";

                            foreach($maps as $map) {
                                if ( $map != "." && $map != ".." ) {
                                    echo "<div id='".$map." 'class='load-map-from-server'> ".$map." </div>";                        
                                }
                            }
                        ?>
                    </div>
                    <div class="col-md-10 preview-canvas-wrapper-div">
                        <div class="preview-map-title-div">
                            <h5 id="preview-map-neighbourhood"></h5>
                            <h5 id="preview-map-name"></h5>
                            <h6 id="preview-map-tileset"></h6>
                        </div>
                        <div class="row preview-map-canvas">
                            <canvas id="preview-map-canvas" class="visible-canvas">
                            </canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>

      </div>
    </div>
  </div>