<div id="map-overview-div" class="row window window-inactive my-auto">
    <div class="row">
        <?php
            $master_neighbourhoods_path = '/master-folder/';
            $master_neighbourhoods = scandir( $_SERVER['DOCUMENT_ROOT'].$master_neighbourhoods_path );
            foreach($master_neighbourhoods as $master_neighbourhood) {
                if ( $master_neighbourhood != "." && $master_neighbourhood != ".." ) {  
                    echo "<button id='".$master_neighbourhood."'-overview-button' class='btn btn-large btn-success select-map-for-overview-button'>".$master_neighbourhood."</button>";                        
                }
            }
        ?>      
    </div>
    <div id="map-overview-canvas-wrapper" class="map-overview-canvas-wrapper">
            
    </div>
</div>