<div id="welcome-div" class="col-sm-12 window-active">
    <div class="row p-3">
        <div class="offset-sm-2 col-sm-10 col-md-4 p-3">
            <h3 class="text-center">
                Welcome, <?php 
                if ( isset($_SESSION["username"])) {
                    echo $_SESSION["username"];
                } else {
                    var_dump($_SESSION);
                }
                ?>
            </h3>
            <hr/>
        </div>
    </div>
    <div class="row">
        <div class="offset-sm-2 col-sm-10 col-md-4">
            <button id="new-map-button" class="mt-5 btn btn-success btn-lg btn-block navigation-button">
                Create new map
            </button>
        </div>
    </div>
    <div class="row">
        <div class="offset-sm-2 col-sm-10 col-md-4">
            <button id="load-map-button" data-toggle="modal" data-target="#loadMapModal" class="mt-5 btn btn-success btn-lg btn-block">
                Load map
            </button>
        </div>
    </div>
    <div class="row">
        <div class="offset-sm-2 col-sm-10 col-md-4">
            <button id="map-overview-button" class="mt-5 btn btn-success btn-lg btn-block navigation-button">
                Map overview
            </button>
        </div>
    </div>
    <div class="row">
        <div class="offset-sm-2 col-sm-10 col-md-4">
            <button id="manage-neighbourhoods-button" class="mt-5 btn btn-success btn-lg btn-block navigation-button">
                Manage neighbourhoods
            </button>
        </div>
    </div>
</div>